Setup

In [33]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [34]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(4*5*3).reshape(4,5,3)
arr_3d.shape


(4, 5, 3)

**Explain:**
- What does `.shape` represent?
it tells us the dimensions of the array, basically how many elements along each axis.
- Why does contiguous memory matter?
contiguous memory matter becuase it lets the cpu and cache work efficiently

Section 1.2 — dtype & Memory

In [37]:
# TODO:
# Create two arrays with same values but different dtypes
base = np.arange(1000)
arr_int = base.astype(np.int64)
arr_float = base.astype(np.float64)

In [38]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print('int bytes :', arr_int.nbytes)
print('float bytes :', arr_float.nbytes)

int bytes : 8000
float bytes : 8000


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?
type selection controls memory footprint, speed, numerical stability and hardware compatibility. At scale, the wrong type silently kills performance or accuracy.


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [39]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(20).reshape(10, 2)
A_slice = A[::2]


In [40]:
# TODO:
# Modify A_slice and observe A
A_slice[0,0] = -999
print('A_slice:',A_slice)
print('A:', A)

A_slice: [[-999    1]
 [   4    5]
 [   8    9]
 [  12   13]
 [  16   17]]
A: [[-999    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]
 [  10   11]
 [  12   13]
 [  14   15]
 [  16   17]
 [  18   19]]


Explain:
- Why did the original array change (or not)?
the original array changed because silcing in numPy returns a view and not a copy

Section 2.2 — Boolean Masking

In [41]:
# TODO:
# Create random array of size 1000

X = np.random.rand(1000)


In [42]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask
mean_val = X.mean()
mask = X > mean_val
result = X[mask]



In [43]:
# TODO:
# Replace negative values with 0 (no loops)

X[X<0]=0

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [44]:
# TODO:
# Create A (1000, 50) and b (50,)

A = np.random.rand(1000, 50)
b = np.random.rand(50)


In [45]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required
A + b

array([[0.58724442, 1.19844122, 1.12350321, ..., 0.51615134, 0.76912728,
        1.14177407],
       [1.28014366, 0.82892571, 0.69282552, ..., 0.99051691, 1.04674366,
        1.68712217],
       [1.29070471, 0.91238512, 0.99192864, ..., 0.72359814, 1.37597057,
        1.64004977],
       ...,
       [1.19125215, 1.72406282, 1.00816016, ..., 0.72797222, 0.78437612,
        1.54797712],
       [1.38976737, 0.80677341, 0.60265797, ..., 1.00923249, 1.48196348,
        0.86729316],
       [1.27967001, 1.04255214, 1.00688569, ..., 0.73210332, 0.75986048,
        0.93794832]])

In [46]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind
row_sums = A.sum(axis=1, keepdims=True)
A_norm = A/row_sums


Explain broadcasting step-by-step.
broadcasting lets numpy do element wise operations on different shapes without copying data.
align shapes from the right
dimensions are compatible if they are equal or one of them is 1
result shape = max per dimension
dimensions with 1 are repeated logically


Section 3.2 — Broadcasting Trap

In [47]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it

A = np.random.rand(1000, 50)
c = np.random.rand(1000)
#A + c -> we fix this using. see below
A + c[:, None]


array([[1.40203823, 0.77150548, 0.92475836, ..., 1.02285583, 1.11570835,
        1.29332407],
       [0.74806763, 0.71447216, 1.14598744, ..., 1.31086858, 0.8799414 ,
        1.08000392],
       [0.84412104, 1.2568502 , 1.25343415, ..., 0.72597198, 1.5118242 ,
        1.37604022],
       ...,
       [1.11687031, 0.74119983, 0.66417808, ..., 0.63266493, 0.84584021,
        1.0223184 ],
       [1.55311897, 0.82325794, 1.14314852, ..., 1.11884246, 1.30518241,
        0.8779526 ],
       [1.9379389 , 1.81201398, 1.86006096, ..., 1.78137988, 1.46524847,
        1.7010671 ]])

What was wrong with the original shapes?
the last decimal didnt match and neither was 1.

Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [48]:
# TODO:
# Create large array X of size 1,000,000

X = np.empty(1_000_000)


In [49]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
X = [i for i in range(1_000_000)]
start = time.time()
total = 0
for x in X:
  total += x
for i in range(len(X)):
  X[i] /= total

end = time.time()
print("time:", end-start)



time: 0.2591080665588379


In [50]:
# TODO:
# Normalize using vectorization
X = np.arange(1_000_000, dtype=float)
start = time.time()
X = X/X.sum()
end = time.time()
print("time:", end-start)


time: 0.003983974456787109


Why is vectorization faster?
vectorization is faster because numpy executes the operation in optimized c using contiguous memory and simd, avoiding python loop overhead.


Task 4.2: Pairwise Distance (FAANG Classic)

In [51]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    sq_norms = np.sum(X**2, axis=1, keepdims=True)
    dist_sq = sq_norms + sq_norms.T - 2 * X @ X.T
    return np.sqrt(dist_sq)


Section 5 — Numerical Stability

Task 5.1: Softmax

In [52]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    exp_X = np.exp(X)
    return exp_X/np.sum(exp_X)


In [53]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    X_shift = X - np.max(X, axis=1, keepdims=True)
    exp_X = np.exp(X_shift)
    return exp_X / np.sum(exp_X, axis=1, keepdims=True)


Why does subtracting max work?
because softmax is invariant to adding or subtracting the same constant form all inputs

Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [54]:
# TODO:
# Try valid and invalid matrix multiplications

A = np.random.rand(3, 4)
B = np.random.rand(4, 2)
C = np.random.rand(3, 2)

print("valid A @ B shape:", (A @ B).shape)

try:
  A @ C
except ValueError as e:
  print("invalid A @ C error:", e)

valid A @ B shape: (3, 2)
invalid A @ C error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)


Explain difference between dot, @, and matmul.
@ is the python operator for matrix multiplication and is equivalent to np.matmul. Both follow standard linear algebra rules and support matrix-matrix, matrix-vector, and vector-vector multiplication, with consistent behavior across dimensions.
np.dot is an older, overloaded function whose behavior depends on the input dimensions: it computes a dot product for 1d arrays, matrix multiplication for 2d arrays, and a sum-product over the last axes for highrt-dimensional arrays. For clarity ans correctness in linear algebra, @ or np.matmul is preferred over np.dot.


Task 6.2: Solving Linear Systems

In [55]:
# TODO:
# Solve Ax = b and verify solution
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("x:", x)
print("A @ x:", A @ x)
print("b:", b)

x: [2. 3.]
A @ x: [9. 8.]
b: [9 8]


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [56]:
# TODO:
# Compare in-place vs out-of-place operations
start = time.time()
Y = X / X.sum()
print("out-of-place time:", time.time()-start)

start = time.time()
X /= X.sum()
print("in-place time:", time.time()-start)



out-of-place time: 0.004609584808349609
in-place time: 0.0026640892028808594


Task 7.2: Strides

In [57]:
# TODO:
# Inspect array strides and explain
A = np.arange(12).reshape(3,4)
print("shape:", A.shape)
print("strides:", A.strides)


shape: (3, 4)
strides: (32, 8)


Section 8 — Mini Case Study

In [58]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

def top_k_eigenvectors(X, k):
  mu = X.mean(axis=0, keepdims=True)
  sigma = X.std(axis=0, keepdims=True)
  sigma[sigma==0]=1.0
  Xn = (X-mu)/sigma

  n = Xn.shape[0]
  C = (Xn.T @ Xn)/(n-1)

  evals, evecs = np.linalg.eigh(C)
  idx = np.argsort(evals)[::-1]
  topk_vecs = evecs[:, idx[:k]]
  return Xn, C, topk_vecs

Explain each step and its ML relevance.
feature normalization rescales each column to zero mean and unit variance so models that rely on distances, variance, or gradients are well-conditioned and no single feature dominates learning. Computing the covariance matrix captures how features vary together and forms the basis of pca by summarizing second-order structure in a compact (dxd) representation. Extracting the top-k eigenvectors selects the directiosn of maximum variance, enabiling dimensionality reduction that improves generalization, reduces noise, and speeds up downstream training.


1. Where did NumPy save memory?
numby saves memory through broadcasting when subtracting the mean and dividing by the standard deviation, avoiding replication of (1xd) arrays across all rows, and by computing covariance as XTX, which yields a small (dxd) matrix rather than any large pairwise structure; additionally, using a symmetric eigen-solver(eigh) exploits matrix structure to avoid unnecessary storage and computation.

2. Where did it avoid Python overhead?
python overhead is avoided by vectorized operations(mean, std, elementwise arithmetic) that run in optimized C loops, and using BLAS/LAPACK for matrix multiplication and eigen-decomposition, eliminating per-element python loops and leveraging low-level, cache-efficient, simd-optimized routines.

3. Which operation would break at scale?
at very large feature dimensions, forming the covariance matrix and especially eigen-decomposition become infeasible due to O(d^2) memory and O(d^3) time, while at very large sample sizes the main failiure point is holding full data or normalized copy in memory, requiring streaming, randomsized svd, or incremental pca instead of full covariance and eigensolvers.
