Setup

In [29]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [46]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(0,100)
arr_1d



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = np.reshape(arr_1d,(10,10))


In [48]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(4*5*3).reshape((4,5,3))
print (arr_3d)
print (arr_3d.shape)

#Reshape represents a different view of the same data (no change in memory as to how the data is stored)
# .shape is a tuple containing the information about number of dimensions and size of each dimension
#contigous memory matters because access becomes easier and faster


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]
(4, 5, 3)


**Explain:**
- What does `.shape` represent?
- Why does contiguous memory matter?


Section 1.2 — dtype & Memory

In [49]:
# TODO:
# Create two arrays with same values but different dtypes

values = [1,2,3,4,5]

arr_int = np.array(values, dtype=np.int32)
arr_float = np.array(values, dtype=np.float64)

print (arr_int.nbytes)
print (arr_float.nbytes)


20
40


In [50]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print (arr_int.nbytes)
print (arr_float.nbytes)

#Dtype selection matters because it dictactes the memory footprint of the model and since we are VRAM restricted with huge models, it makes a big difference


20
40


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [51]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.random.random((6,6))
A_slice = A[::2]
A_slice

array([[0.70026869, 0.61420103, 0.34160371, 0.29131651, 0.43881848,
        0.42472774],
       [0.80613031, 0.69337134, 0.39595895, 0.22174769, 0.70933216,
        0.30198801],
       [0.68922066, 0.25939471, 0.59797315, 0.92288321, 0.36992352,
        0.41511954]])

In [52]:
# TODO:
# Modify A_slice and observe A

print (A)
print (A_slice)

A_slice[0] = np.zeros((6))

print (A)
print (A_slice)

#The original array also did chance. Slicing is just a view so same memory is being used to represent the view as well.


[[0.70026869 0.61420103 0.34160371 0.29131651 0.43881848 0.42472774]
 [0.81477974 0.03936929 0.23539199 0.91421449 0.81499283 0.75168936]
 [0.80613031 0.69337134 0.39595895 0.22174769 0.70933216 0.30198801]
 [0.4640295  0.11192293 0.730514   0.07999003 0.39528669 0.60853718]
 [0.68922066 0.25939471 0.59797315 0.92288321 0.36992352 0.41511954]
 [0.13916164 0.62825497 0.11701403 0.94976483 0.51520192 0.75427093]]
[[0.70026869 0.61420103 0.34160371 0.29131651 0.43881848 0.42472774]
 [0.80613031 0.69337134 0.39595895 0.22174769 0.70933216 0.30198801]
 [0.68922066 0.25939471 0.59797315 0.92288321 0.36992352 0.41511954]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.81477974 0.03936929 0.23539199 0.91421449 0.81499283 0.75168936]
 [0.80613031 0.69337134 0.39595895 0.22174769 0.70933216 0.30198801]
 [0.4640295  0.11192293 0.730514   0.07999003 0.39528669 0.60853718]
 [0.68922066 0.25939471 0.59797315 0.92288321 0.36992352 0.41511954]
 [0.13916164 0.62825497 0.117014

Explain:
- Why did the original array change (or not)?


Section 2.2 — Boolean Masking

In [53]:
# TODO:
# Create random array of size 1000

#X = np.random.rand(1000)
rng = np.random.default_rng(0)
X = rng.standard_normal(1000)


In [54]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask

mean = np.mean(X)
print (mean)

greater_than_mean_locs = np.where(X>mean)

greater_than_mean = X[greater_than_mean_locs]
print (greater_than_mean.shape[0])



-0.04802827676298692
488


In [55]:
# TODO:
# Replace negative values with 0 (no loops)

#new_X = np.where(X<0,0)
X_greater_than_zero = X.copy()
X_greater_than_zero[X < 0] = 0
print (np.mean(X_greater_than_zero))
print (np.max(X_greater_than_zero))
print (np.min(X_greater_than_zero))

0.36458850491995626
3.0660367390488967
0.0


Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [56]:
# TODO:
# Create A (1000, 50) and b (50,)

A = np.arange(50*1000).reshape(1000,50)
b = np.arange(50)


In [57]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required

C = A + b
print (C.shape)

# Broadcasting helps perform operations between arrays of different sizes
# IT starts by trying to match sizes from right most dimension for each of the arrays
# if the size is a match, then it moves to the left.It keeps moving to the left until at least one of the arrays runs out of dimensions, and from then on, the array with lower dimensiosn - it gets added with as many dimensions as the bigger array has (each missing dimension with size same as the other array's size for that dimension)
# If the size is not a match, it checks if one of them is has size 1. If it does, then it expands that one to the size of the other one
# If neither of them are size 1, then we get size mismatch error

(1000, 50)


In [58]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind

X = np.random.rand(10,4)

Y = (X- np.mean(X,axis=1,keepdims=True))/np.std(X,axis=1,keepdims=True)

print (X.shape)
print (Y.shape)

print (X)
print (Y)


(10, 4)
(10, 4)
[[0.65942378 0.86320994 0.85122074 0.87620433]
 [0.81553265 0.13105226 0.32206586 0.91728327]
 [0.72887075 0.3422561  0.67789451 0.95483049]
 [0.6647133  0.18623699 0.10309518 0.34054133]
 [0.87179946 0.35486838 0.8773279  0.08945228]
 [0.82479313 0.47520278 0.51133332 0.74667472]
 [0.44833564 0.67381606 0.10177164 0.98231948]
 [0.70685753 0.69458105 0.8717622  0.60155332]
 [0.0286299  0.61313437 0.00749611 0.02273768]
 [0.98708905 0.16621131 0.57841319 0.72568094]]
[[-1.72346133  0.57071509  0.43574349  0.71700276]
 [ 0.81790861 -1.26290979 -0.68222902  1.1272302 ]
 [ 0.24153374 -1.52343288  0.00881786  1.27308128]
 [ 1.58964274 -0.64043898 -1.02794625  0.07874249]
 [ 0.95286616 -0.57004382  0.96915328 -1.35197561]
 [ 1.24052818 -1.09997409 -0.85808067  0.71752658]
 [-0.32106704  0.38025808 -1.39900561  1.33981456]
 [-0.12158625 -0.2477507   1.57312652 -1.20378957]
 [-0.54205293  1.73127154 -0.62424897 -0.56496964]
 [ 1.25392999 -1.50757142 -0.1208898   0.37453124]]


Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [66]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it
col = np.arange(1000)

try :
  sum = A + col
except Exception as e :
  print ("shape mismtach")
  sum = A + col.reshape(1000,1)

# a dimension was missing and the the wrong dimensions were being compared

shape mismtach


What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [67]:
# TODO:
# Create large array X of size 1,000,000

rng = np.random.default_rng(2)
X = rng.standard_normal(1000000)


In [68]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it

import time

mean = X.mean()
sigma = X.std()

t0 = time.time()
output = np.empty_like(X)

for i in range(X.shape[0]) :
  output[i] = (X[i]-mean)/sigma

print("Time taken = ", time.time()-t0)



Time taken =  0.42021894454956055


In [69]:
# TODO:
# Normalize using vectorization

t1 = time.time()
output_vec = (X - mean)/sigma
print ("Time taken = ", time.time()-t1)

print (np.allclose(output, output_vec))

#Vectorization is faster due to contiguous memory allocation and hence faster access


Time taken =  0.00632929801940918
True


Why is vectorization faster?


Task 4.2: Pairwise Distance (FAANG Classic)

In [70]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    X @ X.T

array = np.random.rand(10,10)
pairwise_dist = pairwise_distance(array)


Section 5 — Numerical Stability

Task 5.1: Softmax

In [71]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    return np.exp(X) / np.sum(np.exp(X))


In [72]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    max_row = np.max(X,axis=1, keepdims=True)
    return np.exp(X-max_row) / np.sum(np.exp(X)-max_row)


#Subtracting max works because it ensures non of the values are very large (e ^ value) can get very large, but if we substract e ^ (value-max_value) ..then the number does not get too big

In [73]:
array = np.random.rand(10,10)

softmax_naive_vec = softmax_naive(array)
softmax_stable_vec = softmax_stable(array)

print (softmax_naive_vec)
print (softmax_stable_vec)

[[0.00857823 0.00999747 0.0093323  0.01303005 0.00659043 0.00704983
  0.01514848 0.0062399  0.00801706 0.00841145]
 [0.01242799 0.01141508 0.01459328 0.01063999 0.00890319 0.01066012
  0.01320747 0.00736398 0.01418452 0.01571419]
 [0.01240301 0.00789154 0.01547108 0.01564569 0.01525608 0.00783813
  0.01327359 0.00908999 0.00977714 0.01273855]
 [0.00936996 0.00803814 0.00605588 0.01111987 0.00626161 0.01174034
  0.0129445  0.00913139 0.00668124 0.0094293 ]
 [0.01314678 0.01034702 0.00766051 0.01522549 0.01037044 0.00876899
  0.01146373 0.01500722 0.00637505 0.00918507]
 [0.00878433 0.0147157  0.00629936 0.01051176 0.01132914 0.00634799
  0.00837451 0.0071168  0.01056207 0.00814299]
 [0.01076793 0.00836465 0.01046569 0.01468694 0.01278659 0.01302921
  0.01017687 0.01168694 0.00590484 0.0095709 ]
 [0.01106039 0.00658603 0.00816666 0.00721452 0.0073106  0.00603511
  0.00695286 0.01103894 0.0062714  0.00730501]
 [0.00712773 0.00892829 0.00733104 0.00846968 0.01246491 0.00928381
  0.01559789

Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [74]:
# TODO:
# Try valid and invalid matrix multiplications
A = np.random.randint(0,10, (10,10))
B = np.random.randint(0,10,(10,6))

print (A)
print (B)

C = A @ B
D = np.dot(A,B)
E = np.matmul(A,B)

print (np.allclose(C,D))
print (np.allclose(C,E))
print (np.allclose(D,E))

#  @ and Matmul are exactly the same -> matrix multiplication - just different symbols
# np.dot is different - it does element wise multiplicaiton in 1D, matrix multiplcation in 2D

[[2 3 9 3 0 3 7 6 6 2]
 [6 2 6 3 3 8 4 4 4 2]
 [7 7 6 6 9 2 4 3 7 5]
 [5 3 0 7 3 2 7 9 8 2]
 [3 6 6 5 7 1 7 2 9 5]
 [2 3 3 1 7 1 3 0 4 9]
 [7 8 7 6 6 9 4 2 2 0]
 [6 5 1 6 9 0 5 5 9 7]
 [2 5 4 2 8 0 7 7 6 8]
 [9 4 8 9 9 2 4 7 9 1]]
[[1 2 6 4 9 5]
 [8 4 1 2 9 0]
 [8 3 0 8 2 2]
 [8 6 0 7 9 6]
 [7 1 2 7 1 4]
 [9 5 1 4 6 3]
 [8 4 1 2 5 0]
 [8 0 5 0 7 5]
 [8 1 7 1 0 5]
 [5 8 9 6 2 6]]
True
True
True


[link text](https://)Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [75]:
# TODO:
# Solve Ax = b and verify solution

A = np.random.rand(5,5)
b = np.random.rand(5,1)

x = np.linalg.solve(A,b)

#verification -> After finding x, Ax should be equal to b
print (np.allclose(A@x, b))

True


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [77]:
# TODO:
# Compare in-place vs out-of-place operations

X = np.random.rand(1000000)

t0 = time.time()
Y = X + 1
t1 = time.time()
X += 1
t2 = time.time()

print ("In place = ", t2-t1)
print ("Out of place = ", t1-t0)

In place =  0.0011148452758789062
Out of place =  0.0018432140350341797


Task 7.2: Strides

In [79]:
# TODO:
# Inspect array strides and explain

A = np.arange(120,dtype=np.int64).reshape(20,6)

print (A.shape)
print (A.strides)

print (A[:,::2].shape)
print (A[:,::2].strides)

print (A[::2, :].shape)
print (A[::2, :].strides)

# Strides are basically capturing how many bits of data to reach the next row, column.
# When slices, we need to skip over some data to go to next data -> column slice - double the data in column bits and when row slices, double the data in row bits

(20, 6)
(48, 8)
(20, 3)
(48, 16)
(10, 6)
(96, 8)


Section 8 — Mini Case Study

In [88]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

X = np.random.rand(10000,100)

#X = (X - np.mean(X))/ np.std(X)

mean = np.mean(X, axis=0,keepdims=True)
std = np.std(X, axis=0,keepdims=True)


X = (X-mean) / std

cov = (X.T @ X) /(X.shape[0] - 1)
eig_vals, eig_vecs = np.linalg.eigh(cov)

k = 5

top_indices = np.argsort(eig_vals)[-k: ][::-1]
print (top_indices)

top_eigenvectors = eig_vecs[top_indices]
print (top_eigenvectors.shape)
#eigen = np.eigenvectors(X)
#print (cov, eigen)

# First we are normalizing the features across all rows.
# Then we compute the variance matrix
# Eigen decomposition of this co-variance matrix is telling us which direction has the highest variance
# Selecting the top-k eigen vectors basically gives us the reduced diension representation of the most important dimensions of the data represented in a different space
# This is basically achieving PCA

[99 98 97 96 95]
(5, 100)


Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
