Setup

In [3]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [4]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)


In [5]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = np.reshape(arr_1d, (10, 10))


In [6]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.reshape(arr_1d[:60], (4, 5, 3))


**Explain:**
- What does `.shape` represent?
- It represents multiple dimensions of the array. array.shape provies the dimensions in form of a tuple.

- Why does contiguous memory matter?
- It is easy and faster to accress data randomly.

Section 1.2 — dtype & Memory

In [46]:
# TODO:
# Create two arrays with same values but different dtypes

arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int64)
arr_float = np.array([1, 2, 3, 4, 5], dtype=np.float64)


In [47]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
arr_int_nbytes = arr_int.nbytes
arr_float_nbytes = arr_float.nbytes

# Print memory usage
print(f"Integer array memory usage: {arr_int_nbytes} bytes")
print(f"Float array memory usage: {arr_float_nbytes} bytes")


Integer array memory usage: 40 bytes
Float array memory usage: 40 bytes


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?

- For large ML pipelines, there will be space contraints. but most important factor is, if size of data is larger it takes more time for processing (Cache space may not be enough to store huge data, so everytime data has to be retrived from storage disk). So it slows down the process.

Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [9]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(20).reshape(10, 2)
A_slice = A[::2, :]  # Slicing every alternate row


In [10]:
# TODO:
# Modify A_slice and observe A
A_slice += 100
print("Modified A_slice:")
print(A_slice)
print("Original A after modifying A_slice:")
print(A)


Modified A_slice:
[[100 101]
 [104 105]
 [108 109]
 [112 113]
 [116 117]]
Original A after modifying A_slice:
[[100 101]
 [  2   3]
 [104 105]
 [  6   7]
 [108 109]
 [ 10  11]
 [112 113]
 [ 14  15]
 [116 117]
 [ 18  19]]


Explain:
- Why did the original array change (or not)?


- Original Array changed because, in numpy, it views insted of copying.

Section 2.2 — Boolean Masking

In [11]:
# TODO:
# Create random array of size 1000

X = np.random.rand(1000)

X


array([4.13997266e-01, 9.08854678e-01, 5.86355999e-01, 6.15330999e-01,
       9.95953667e-01, 9.52717368e-01, 4.92306158e-01, 9.06382355e-01,
       8.86149378e-01, 1.20805803e-02, 4.69039186e-02, 7.94027446e-01,
       5.10065538e-01, 1.45599500e-01, 9.02054604e-01, 7.34780719e-01,
       7.24114636e-01, 7.57439699e-01, 7.17579601e-01, 8.18369468e-01,
       6.79259114e-02, 9.11931023e-01, 1.83928254e-01, 9.87983261e-01,
       8.20276779e-01, 8.68265807e-02, 9.71307481e-01, 6.87568804e-02,
       4.60523667e-01, 1.02692215e-01, 6.48413729e-01, 2.49827007e-01,
       9.28241085e-01, 1.45730275e-01, 4.56741575e-01, 9.66747577e-01,
       9.56984721e-01, 3.22973818e-01, 7.71006983e-01, 3.05667345e-03,
       3.05880882e-01, 4.53131174e-01, 9.16087827e-01, 5.82613493e-01,
       7.54894881e-01, 5.71930087e-02, 7.98973298e-01, 6.08817967e-01,
       4.71522180e-01, 8.20838542e-01, 9.78125374e-01, 9.32458467e-01,
       6.92972562e-01, 1.72548832e-01, 8.77709886e-01, 5.92074995e-01,
      

In [12]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask

X_mean = np.mean(X)
X_gt_mean = X[X > X_mean]
X_gt_mean


array([0.90885468, 0.586356  , 0.615331  , 0.99595367, 0.95271737,
       0.90638235, 0.88614938, 0.79402745, 0.51006554, 0.9020546 ,
       0.73478072, 0.72411464, 0.7574397 , 0.7175796 , 0.81836947,
       0.91193102, 0.98798326, 0.82027678, 0.97130748, 0.64841373,
       0.92824109, 0.96674758, 0.95698472, 0.77100698, 0.91608783,
       0.58261349, 0.75489488, 0.7989733 , 0.60881797, 0.82083854,
       0.97812537, 0.93245847, 0.69297256, 0.87770989, 0.592075  ,
       0.84607302, 0.73014363, 0.83917823, 0.7074263 , 0.53629991,
       0.64157354, 0.75704451, 0.65155912, 0.50612042, 0.97162051,
       0.88591537, 0.74335707, 0.89169164, 0.94074551, 0.86050877,
       0.53441253, 0.86764139, 0.67989038, 0.55186463, 0.72906913,
       0.79708463, 0.60718959, 0.7678161 , 0.64688729, 0.66272994,
       0.89892228, 0.8425678 , 0.6174359 , 0.90160564, 0.86970413,
       0.56938303, 0.63075029, 0.88745001, 0.82051165, 0.55968621,
       0.96214968, 0.85134983, 0.84384806, 0.55318488, 0.56296

In [13]:
# TODO:
# Replace negative values with 0 (no loops)

X[X < 0] = 0

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [16]:
# TODO:
# Create A (1000, 50) and b (50,)

A = np.random.rand(1000, 50)
b = np.random.rand(50,)

print("A :",A)
print("b :",b)

A : [[0.17478758 0.54042163 0.19131527 ... 0.04798372 0.47467415 0.71717977]
 [0.46978516 0.30390762 0.52110097 ... 0.21817473 0.56729076 0.92058806]
 [0.06736564 0.06233146 0.20458861 ... 0.27922477 0.77282151 0.99748437]
 ...
 [0.98440086 0.12273693 0.0930983  ... 0.24761168 0.49111425 0.55225812]
 [0.76207202 0.95516421 0.03697265 ... 0.00828123 0.14281514 0.14991576]
 [0.07213703 0.65722035 0.73384401 ... 0.89464511 0.05566557 0.97512124]]
b : [0.8447287  0.6569498  0.50856674 0.0499397  0.77185652 0.80261808
 0.1166871  0.97272962 0.33055914 0.57335382 0.9731744  0.79630516
 0.51659575 0.800989   0.48463457 0.24980965 0.18571306 0.69740609
 0.39843285 0.16953648 0.43765697 0.20160795 0.92056421 0.21066192
 0.43244426 0.85334036 0.70740323 0.48558063 0.87067287 0.08545531
 0.04397452 0.32213205 0.88923158 0.52417012 0.7918358  0.48495809
 0.88630313 0.72775492 0.18403624 0.09457348 0.33130759 0.80172845
 0.8754341  0.97148053 0.32659521 0.34247534 0.80092766 0.82445228
 0.7585079  

In [18]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required

C = A + b
print("C :",C)


C : [[1.01951628 1.19737142 0.69988201 ... 0.87243601 1.23318205 0.97032177]
 [1.31451386 0.96085742 1.02966771 ... 1.04262701 1.32579866 1.17373006]
 [0.91209434 0.71928126 0.71315535 ... 1.10367705 1.53132941 1.25062637]
 ...
 [1.82912956 0.77968672 0.60166504 ... 1.07206396 1.24962215 0.80540012]
 [1.60680072 1.61211401 0.54553939 ... 0.83273352 0.90132304 0.40305776]
 [0.91686573 1.31417015 1.24241076 ... 1.7190974  0.81417347 1.22826324]]


In [19]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind

A_row_mean = A.mean(axis=1, keepdims=True)
A_row_std = A.std(axis=1, keepdims=True)
A_normalized = (A - A_row_mean) / A_row_std
A_normalized

array([[-1.1843552 ,  0.00696895, -1.13050398, ..., -1.59751282,
        -0.20725223,  0.58288974],
       [-0.00519656, -0.60102333,  0.17912816, ..., -0.90897312,
         0.34504039,  1.61407291],
       [-1.48347103, -1.49961411, -1.04343905, ..., -0.80410378,
         0.77870957,  1.49913449],
       ...,
       [ 1.71528674, -1.40570286, -1.51305543, ..., -0.95340029,
        -0.0714219 ,  0.15004426],
       [ 0.86417555,  1.51326329, -1.57327727, ..., -1.66972471,
        -1.21748318, -1.19361412],
       [-1.33281062,  0.62162282,  0.87757927, ...,  1.41472507,
        -1.38783247,  1.68355042]])

Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [23]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it

a = np.random.rand(3, 4)
b = np.random.rand(5)
# This will raise an error
# c = a + b  # Uncommenting this line will trigger a broadcasting error
#finxing by reshaping b
b_reshaped = b.reshape(1, 5)
c = a + b_reshaped[:, :4]  # Adjusted to match dimensions   

print("c :",c)

c : [[1.29526485 1.37219729 1.22287161 1.66595168]
 [1.43439599 1.23665174 1.19496267 0.99444956]
 [1.12361751 1.0142791  1.73829561 1.73060615]]


What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [25]:
# TODO:
# Create large array X of size 1,000,000

X = np.random.rand(1000000)
X


array([0.46621393, 0.41026757, 0.57421978, ..., 0.84283679, 0.42426232,
       0.05179738])

In [35]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
X_mean = np.mean(X)
X_std = np.std(X)
X_normalized_loop = np.empty_like(X)
start_time = time.time()
for i in range(X.shape[0]):
    X_normalized_loop[i] = (X[i] - X_mean) / X_std
end_time = time.time()
print(f"Time taken using loop: {end_time - start_time} seconds")

Time taken using loop: 0.21214890480041504 seconds


In [36]:
# TODO:
# Normalize using vectorization
# Time it
X_mean = np.mean(X)
X_std = np.std(X)
start_time = time.time()
X_normalized_vectorized = (X - X_mean) / X_std
end_time_vectorized = time.time()
X_normalized_vectorized
print(f"Time taken using vectorization: {end_time_vectorized - start_time} seconds")


Time taken using vectorization: 0.0034034252166748047 seconds


Why is vectorization faster?

- Because it utilizes SIMD (Single Instruction, Multiple data)

Task 4.2: Pairwise Distance (FAANG Classic)

In [48]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    sum_X = np.sum(np.square(X), axis=1)
    D = np.sqrt(sum_X[:, np.newaxis] + sum_X[np.newaxis, :] - 2 * np.dot(X, X.T))
    return D

print("D :",pairwise_distance(np.random.rand(5, 3)))

D : [[0.         0.61919029 0.20221121 0.38420591 0.23339088]
 [0.61919029 0.         0.51715461 0.70413432 0.61708315]
 [0.20221121 0.51715461 0.         0.54735749 0.37196196]
 [0.38420591 0.70413432 0.54735749 0.         0.21489797]
 [0.23339088 0.61708315 0.37196196 0.21489797 0.        ]]


Section 5 — Numerical Stability

Task 5.1: Softmax

In [49]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    exp_X = np.exp(X)
    sum_exp_X = np.sum(exp_X, axis=1, keepdims=True)
    softmax_X = exp_X / sum_exp_X
    return softmax_X

print("softmax_naive :",softmax_naive(np.random.rand(2, 3)))



softmax_naive : [[0.38538992 0.2237072  0.39090288]
 [0.31226642 0.39165387 0.29607971]]


In [50]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    X_max = np.max(X, axis=1, keepdims=True)
    exp_X = np.exp(X - X_max)
    sum_exp_X = np.sum(exp_X, axis=1, keepdims=True)
    softmax_X = exp_X / sum_exp_X
    return softmax_X
print("softmax_stable :",softmax_stable(np.random.rand(2, 3)))


softmax_stable : [[0.35255124 0.41187702 0.23557174]
 [0.27734662 0.37374409 0.34890929]]


Why does subtracting max work?



Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [40]:
# TODO:
# Try valid and invalid matrix multiplications

A = np.random.rand(3, 4)
B_valid = np.random.rand(4, 5)
B_invalid = np.random.rand(3, 5)
# Valid multiplication
C_valid = np.dot(A, B_valid)
print("C_valid :",C_valid)
# Invalid multiplication will raise an error
# C_invalid = np.dot(A, B_invalid)  # Uncommenting this line will trigger

C_valid : [[1.48878189 1.0077277  1.14220764 1.00087257 0.47630704]
 [1.54764085 1.23902688 1.67118581 1.76608352 1.42245097]
 [1.55029863 1.10312859 1.71285904 1.65757889 1.28417899]]


Explain difference between dot, @, and matmul.

- The difference between these 3 is mostly optimization. dot is oldest while matmul modren optimised version of matrix multipolication.

Task 6.2: Solving Linear Systems

In [ ]:
# TODO:
# Solve Ax = b and verify solution

A = np.random.rand(4, 4)
b = np.random.rand(4,)
x = np.linalg.solve(A, b)
b_reconstructed = np.dot(A, x)
print("x :",x)
print("b_reconstructed :",b_reconstructed)

# Verify solution
assert np.allclose(b, b_reconstructed), "Solution verification failed!"


x : [ 2.36210686  8.33056773 -2.87226558  0.05717203]
b_reconstructed : [0.87431077 0.84565432 0.95245866 0.3495448 ]


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [43]:
# TODO:
# Compare in-place vs out-of-place operations

A = np.random.rand(1000, 1000)

print("A before operations :",A)

# Out-of-place
B = A + 10
# In-place
A += 10

print("B :",B)
print("A after in-place addition :",A)


A before operations : [[0.92586835 0.17738269 0.75145752 ... 0.4145372  0.94763278 0.85733798]
 [0.1487141  0.29912908 0.36930165 ... 0.77255688 0.67410884 0.53549198]
 [0.87538197 0.15175792 0.41625922 ... 0.49495439 0.31394469 0.66883203]
 ...
 [0.4808944  0.14870316 0.23530175 ... 0.24076872 0.36817676 0.60974832]
 [0.13288594 0.55625003 0.23154888 ... 0.60311569 0.37905298 0.2730945 ]
 [0.02305937 0.45345038 0.50291087 ... 0.63459075 0.92444484 0.98735455]]
B : [[10.92586835 10.17738269 10.75145752 ... 10.4145372  10.94763278
  10.85733798]
 [10.1487141  10.29912908 10.36930165 ... 10.77255688 10.67410884
  10.53549198]
 [10.87538197 10.15175792 10.41625922 ... 10.49495439 10.31394469
  10.66883203]
 ...
 [10.4808944  10.14870316 10.23530175 ... 10.24076872 10.36817676
  10.60974832]
 [10.13288594 10.55625003 10.23154888 ... 10.60311569 10.37905298
  10.2730945 ]
 [10.02305937 10.45345038 10.50291087 ... 10.63459075 10.92444484
  10.98735455]]
A after in-place addition : [[10.92586

Task 7.2: Strides

In [44]:
# TODO:
# Inspect array strides and explain

A.strides

(8000, 8)

Section 8 — Mini Case Study

In [45]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

X = np.random.rand(10000, 100)
# Normalize features
X_mean = X.mean(axis=0, keepdims=True)
X_std = X.std(axis=0, keepdims=True)
X_normalized = (X - X_mean) / X_std
# Compute covariance matrix
cov_matrix = np.cov(X_normalized, rowvar=False)
# Extract top-k eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
k = 10  # Number of top eigenvectors to extract
top_k_indices = np.argsort(eigenvalues)[-k:]
top_k_eigenvectors = eigenvectors[:, top_k_indices]
top_k_eigenvectors


array([[ 1.14423524e-01, -4.76254647e-02,  1.44647634e-01,
        -2.70831346e-03,  1.86425991e-02, -9.13271241e-02,
         8.04739279e-02, -4.57238482e-02,  4.37741768e-02,
        -1.79203030e-02],
       [-4.08769032e-02, -7.07523561e-02,  1.74857156e-01,
         5.56899311e-03,  4.32004058e-02,  1.73837518e-01,
        -5.97900614e-03,  1.37358947e-01, -6.14385674e-02,
        -1.40130588e-01],
       [-5.44989229e-02,  8.52473929e-02, -9.48754425e-02,
         2.77738354e-03, -6.66198778e-02, -8.64973642e-02,
         1.12665844e-01, -1.11939439e-01,  1.41156337e-01,
         1.43424544e-01],
       [ 8.60415776e-02,  1.48235968e-01,  7.76577254e-02,
         8.01968242e-02,  2.68327734e-03,  3.70322117e-02,
         7.98870352e-02, -1.29389959e-02,  3.11765078e-02,
        -9.26204959e-02],
       [-1.82593005e-01, -2.50728728e-02, -5.54633747e-02,
         5.70720737e-02, -3.34026471e-02,  5.89356575e-02,
        -7.61619101e-02,  4.21327885e-02,  1.16939661e-01,
        -5.

Explain each step and its ML relevance.


1. Where did NumPy save memory?

- Numpy is based on homogenous data unlike lists python which tend to take datatype with longest memory size as default datatype for list. Numpy is either a int or float.
- For many operations, it views the array insted of copying.

2. Where did it avoid Python overhead?

- Numpy loops run in optimised code of C/Fortron insted of python loops

3. Which operation would break at scale?

- Element wise python level loops and object creation breaks at scale
