Setup

In [65]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [12]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
print(arr_1d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10,10)
print(arr_2d)
print(arr_2d.shape)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(10, 10)


In [15]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(60).reshape(4,5,3)
print(arr_3d)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


**Explain:**
- What does `.shape` represent?
shape represent the number of dimensions of the array
- Why does contiguous memory matter?
continous memory helps easy to find the value of other element as we will have reference of the first value then we can identify another value if we know the data type size.


Section 1.2 — dtype & Memory

In [6]:
# TODO:
# Create two arrays with same values but different dtypes

arr_int = np.arange(60,dtype=int)
arr_float = np.arange(60, dtype=np.float32)
print(arr_int.dtype)
print(arr_int)
print(arr_float.dtype)
print(arr_float)

int64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
float32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59.]


In [7]:
# TODO:
# Compare memory usage
print(arr_int.nbytes)
print(arr_float.nbytes)
# HINT:
# - Use .nbytes


480
240


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [61]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(100).reshape(10,10)
print(A)
A_slice = A[::2]
print(A_slice)



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]]


In [62]:
# TODO:
# Modify A_slice and observe A
for row in range(len(A_slice[:])):
    for col in range(len(A_slice[row])):     
        A_slice[row][col] = A_slice[row][col]*2
print(A)
print(A_slice)


[[  0   2   4   6   8  10  12  14  16  18]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 80  82  84  86  88  90  92  94  96  98]
 [ 50  51  52  53  54  55  56  57  58  59]
 [120 122 124 126 128 130 132 134 136 138]
 [ 70  71  72  73  74  75  76  77  78  79]
 [160 162 164 166 168 170 172 174 176 178]
 [ 90  91  92  93  94  95  96  97  98  99]]
[[  0   2   4   6   8  10  12  14  16  18]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 80  82  84  86  88  90  92  94  96  98]
 [120 122 124 126 128 130 132 134 136 138]
 [160 162 164 166 168 170 172 174 176 178]]


Explain:
- Why did the original array change (or not)?
Original array because it is shallow copy so reference still the same of A. It needs to have deep copy.


Section 2.2 — Boolean Masking

In [73]:
# TODO:
# Create random array of size 1000
rng = np.random.default_rng()
X =rng.random(1000)
print(X)


[0.87419888 0.77967986 0.47907732 0.72089827 0.97772655 0.55808614
 0.42188    0.67981922 0.02727161 0.18430573 0.33405887 0.80956925
 0.00698194 0.77559548 0.66839804 0.79515101 0.66473716 0.55532608
 0.77998446 0.27028612 0.34118722 0.81678915 0.89816179 0.11618375
 0.43697359 0.65258219 0.84252401 0.15397157 0.05616795 0.42534108
 0.44883699 0.21857785 0.09924707 0.51141226 0.81589043 0.03528171
 0.57050328 0.65168385 0.72526189 0.59867107 0.83825377 0.053751
 0.15065045 0.19127685 0.86792833 0.48324572 0.18727374 0.22739447
 0.55775917 0.52271318 0.56836726 0.26700396 0.51433327 0.84548866
 0.05309712 0.70900171 0.37202446 0.77304182 0.16628963 0.9852295
 0.22414712 0.87477779 0.92685207 0.05029271 0.6084053  0.43501199
 0.21621244 0.90864262 0.63993118 0.40250028 0.18836581 0.76993248
 0.47846574 0.24043792 0.45803794 0.46954268 0.11097935 0.64691554
 0.36119912 0.07122099 0.05787468 0.90859549 0.7411869  0.7458736
 0.36482019 0.55421492 0.10560183 0.20330067 0.16713694 0.79162425

In [75]:
# TODO:
# Extract values greater than mean
Xmean = X.mean()
print(Xmean)
XGrtMean = X[X>Xmean]
print(XGrtMean)
# HINT:
# - Mean first
# - Boolean mask




0.505605617683484
[0.87419888 0.77967986 0.72089827 0.97772655 0.55808614 0.67981922
 0.80956925 0.77559548 0.66839804 0.79515101 0.66473716 0.55532608
 0.77998446 0.81678915 0.89816179 0.65258219 0.84252401 0.51141226
 0.81589043 0.57050328 0.65168385 0.72526189 0.59867107 0.83825377
 0.86792833 0.55775917 0.52271318 0.56836726 0.51433327 0.84548866
 0.70900171 0.77304182 0.9852295  0.87477779 0.92685207 0.6084053
 0.90864262 0.63993118 0.76993248 0.64691554 0.90859549 0.7411869
 0.7458736  0.55421492 0.79162425 0.55824346 0.8983605  0.84554621
 0.98747102 0.8479683  0.937534   0.81681621 0.90318756 0.61696262
 0.77093379 0.81432354 0.63875769 0.99689111 0.61560434 0.60583534
 0.97269543 0.84367243 0.77733363 0.85859446 0.77924417 0.73804478
 0.62617852 0.56501241 0.78731986 0.59254198 0.54286634 0.54800939
 0.69447284 0.79026676 0.62920962 0.69033503 0.5210039  0.75983566
 0.68573652 0.66910745 0.61989923 0.66038167 0.5739048  0.92457394
 0.69439129 0.96922978 0.97459639 0.93781227 0

In [ ]:
# TODO:
# Replace negative values with 0 (no loops)

X[X<0] = 0
print(X)



[0.87419888 0.77967986 0.47907732 0.72089827 0.97772655 0.55808614
 0.42188    0.67981922 0.02727161 0.18430573 0.33405887 0.80956925
 0.00698194 0.77559548 0.66839804 0.79515101 0.66473716 0.55532608
 0.77998446 0.27028612 0.34118722 0.81678915 0.89816179 0.11618375
 0.43697359 0.65258219 0.84252401 0.15397157 0.05616795 0.42534108
 0.44883699 0.21857785 0.09924707 0.51141226 0.81589043 0.03528171
 0.57050328 0.65168385 0.72526189 0.59867107 0.83825377 0.053751
 0.15065045 0.19127685 0.86792833 0.48324572 0.18727374 0.22739447
 0.55775917 0.52271318 0.56836726 0.26700396 0.51433327 0.84548866
 0.05309712 0.70900171 0.37202446 0.77304182 0.16628963 0.9852295
 0.22414712 0.87477779 0.92685207 0.05029271 0.6084053  0.43501199
 0.21621244 0.90864262 0.63993118 0.40250028 0.18836581 0.76993248
 0.47846574 0.24043792 0.45803794 0.46954268 0.11097935 0.64691554
 0.36119912 0.07122099 0.05787468 0.90859549 0.7411869  0.7458736
 0.36482019 0.55421492 0.10560183 0.20330067 0.16713694 0.79162425

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [127]:
# TODO:
# Create A (1000, 50) and b (50,)

A = np.arange(50000).reshape(1000,50)
#A.shape = (1000,50)
b = np.arange(50).reshape(50)
#b.shape = (50)
print(A.shape)
print(b.shape)


(1000, 50)
(50,)


In [128]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required
Asumb = A+b
print(Asumb)


[[    0     2     4 ...    94    96    98]
 [   50    52    54 ...   144   146   148]
 [  100   102   104 ...   194   196   198]
 ...
 [49850 49852 49854 ... 49944 49946 49948]
 [49900 49902 49904 ... 49994 49996 49998]
 [49950 49952 49954 ... 50044 50046 50048]]


In [139]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind

Xaxis = A.mean(axis=1)
print(Xaxis.shape)



(1000,)


Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [154]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it
print(A.shape)
col = np.arange(1000).reshape(1000,1)
print(col.shape)
broadcast = A-col
print(A)
print(col)
print(broadcast.shape)
print(broadcast)


(1000, 50)
(1000, 1)
[[    0     1     2 ...    47    48    49]
 [   50    51    52 ...    97    98    99]
 [  100   101   102 ...   147   148   149]
 ...
 [49850 49851 49852 ... 49897 49898 49899]
 [49900 49901 49902 ... 49947 49948 49949]
 [49950 49951 49952 ... 49997 49998 49999]]
[[  0]
 [  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 

What was wrong with the original shapes?
I went through the video to understand this concept. Values should match from righ to left for the broadcast. A shape is (1000,50) and col2 has (1000,1) and output is (1000,50). My question size from right to left which is 50 of A and 1 of col2 is not matching.


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [156]:
# TODO:
# Create large array X of size 1,000,000

X = np.arange(1000000)
print(X.shape)


(1000000,)


In [163]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
Xmean = X.mean()
Xstd = X.std()
tstart = time.time()
result = np.empty_like(X)
for i in range((X.shape[0])):
   result[i] = (X[i] - Xmean) / Xstd
tend = time.time()
print(tend-tstart)




0.35327863693237305


In [167]:
# TODO:
# Normalize using vectorization
X = list(range(1,1000))
tVectStart = time.time()
X = X - Xmean/ Xstd
tVectEnd = time.time()
print(tVectEnd-tVectStart)



0.0014107227325439453


Why is vectorization faster?
Vectorization is faster because we are using the numpy and it executes in C but in my example I have used list (not numpy array) still it is faster. This I didn't completely followed.


Task 4.2: Pairwise Distance (FAANG Classic)

In [183]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    sq = np.sum(X*X,axis=1,keepdims=True)
    print(sq.shape)
    equi = sq + sq.T - 2*(X  @X.T)
    print(equi.shape)
    equi = np.maximum(equi,0.0)
    return equi

input = rng.standard_normal((100,50))
output = pairwise_distance(input)
print(output)


(100, 1)
(100, 100)
[[0.00000000e+00 1.25948399e+02 9.51003799e+01 ... 9.03459342e+01
  1.19976484e+02 7.70459300e+01]
 [1.25948399e+02 0.00000000e+00 8.73904174e+01 ... 8.96371017e+01
  9.66544132e+01 9.53071995e+01]
 [9.51003799e+01 8.73904174e+01 2.84217094e-14 ... 9.17481034e+01
  1.20289231e+02 8.88313780e+01]
 ...
 [9.03459342e+01 8.96371017e+01 9.17481034e+01 ... 0.00000000e+00
  1.01291493e+02 9.33348976e+01]
 [1.19976484e+02 9.66544132e+01 1.20289231e+02 ... 1.01291493e+02
  1.42108547e-14 7.20525840e+01]
 [7.70459300e+01 9.53071995e+01 8.88313780e+01 ... 9.33348976e+01
  7.20525840e+01 0.00000000e+00]]


Section 5 — Numerical Stability

Task 5.1: Softmax

In [189]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    expo = np.exp(X)
    return expo/expo.sum(axis=1,keepdims = True)
    print(expo)
    
softMaxInput = np.array([[1000,1001,1002]])
print(softMaxInput)
softmax_naive(softMaxInput)


[[1000 1001 1002]]


C:\Users\mabotla\AppData\Local\Temp\ipykernel_17324\2584911495.py:5: RuntimeWarning: overflow encountered in exp
  expo = np.exp(X)
C:\Users\mabotla\AppData\Local\Temp\ipykernel_17324\2584911495.py:6: RuntimeWarning: invalid value encountered in divide
  return expo/expo.sum(axis=1,keepdims = True)


array([[nan, nan, nan]])

In [191]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
   Z = X -X.max(axis=1,keepdims=True)
   expo = np.exp(Z)
   return expo/expo.sum(axis=1,keepdims = True)
   
softMaxStableInput = np.array([[1000,1001,1002]])
print(softMaxStableInput)
softmax_stable(softMaxStableInput)

[[1000 1001 1002]]


array([[0.09003057, 0.24472847, 0.66524096]])

Why does subtracting max work?
As we are doing the expo hence we are dividing the max value from each value.


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [199]:
# TODO:
# Try valid and invalid matrix multiplications
#Valid
A_matrix = rng.random((50,5))
B_matrix = rng.random((5,50))
print(A_matrix @ B_matrix)


#Invalid
A_matrix = rng.random((50,5))
B_matrix = rng.random((50,5))
print(B_matrix.shape)
print(A_matrix @ B_matrix)
print(A_matrix.shape)


[[0.65991917 1.13946867 1.01701009 ... 0.25479096 1.09786178 1.2015169 ]
 [1.07817501 2.27190098 1.82707453 ... 1.01321695 1.54252145 1.70884244]
 [1.11359789 2.43025044 1.06459655 ... 1.05945775 1.03245221 1.60492426]
 ...
 [0.52086692 1.57999148 0.70084379 ... 0.6734422  0.73664028 0.96746662]
 [0.90776483 1.58672741 0.92623588 ... 0.65748567 0.57166707 0.95187845]
 [0.91864174 2.12551075 0.93076995 ... 0.7787019  0.91025723 1.36469802]]
(50, 5)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 50 is different from 5)

Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [ ]:
# TODO:
# Solve Ax = b and verify solution
A = rng.standard_normal((5,5))
b = rng.standard_normal((5,5))
x = np.linalg.solve(A,b)
residual = np.linalg.norm(A @ x -b)

[[-0.59090244 -1.12873966 -0.52008498  0.76964715  2.27409553]
 [-0.17724264  0.56051167  1.53066253 -0.18580387 -0.32416517]
 [-0.61462078 -1.67405823  0.04023454 -0.11381072 -0.31714223]
 [-0.24015211 -0.40041368  0.67525724 -2.48878405 -0.47053518]
 [-0.44422826 -0.05915167 -0.95756547  1.55175023  0.05768348]]
[[ 0.43476561 -0.9947996   0.06973667  0.3068768  -2.50522188]
 [-0.1907279   0.65814867 -1.14891988  0.29693155  1.40185819]
 [ 0.23205644 -0.874187   -1.16772635 -0.40201772 -1.51061688]
 [ 0.4575917   0.15381627  0.34542685  0.93567173 -0.80477296]
 [-0.17285563  0.25048706 -0.93482245  0.07426966 -0.482287  ]]


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [ ]:
# TODO:
# Compare in-place vs out-of-place operations

X = rng.standard_normal(200000)
XIn = X.copy()
tOutStart = time.time()
Out_result = X + 1.0
print('Out of place :',time.time()-tOutStart)

tInStart = time.time()
XIn += 1.0
print('In of place :',time.time()-tInStart)

Out of place : 0.0004432201385498047
In of place : 0.0005381107330322266


Task 7.2: Strides

In [215]:
# TODO:
# Inspect array strides and explain
A_strides = np.arange(50).reshape(10,5)
print(A_strides.shape)
print(A_strides.strides)

(10, 5)
(40, 8)


Section 8 — Mini Case Study

In [220]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors
X_eig = rng.standard_normal((100000,100))
mu = X_eig.mean(axis=0,keepdims=True)
sigma = X_eig.std(axis=0, keepdims=True)
X_eign = (X_eig - mu)/sigma

Conv = (X_eign.T @ X_eign) / (X_eign.shape[0]-1)

eigvals, eigvecs = np.linalg.eigh(Conv)
k=5
top_idx = np.argsort(eigvals)[-k:][::-1]
top_idx



array([99, 98, 97, 96, 95])

Explain each step and its ML relevance.


1. Where did NumPy save memory?
It is built on C and it has continous memory allocation.
2. Where did it avoid Python overhead?
Using numpy vectorization has avoided the python overhead.
3. Which operation would break at scale?
exponential will break in the softmax if we don't delete the max value. But what would happen if the value is 0 and max is 10001 so difference still would be negative max.
