Setup

In [1]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [2]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
arr_1d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10, 10)
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(4*5*3).reshape(4, 5, 3)
arr_3d


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

**Explain:**
- What does `.shape` represent?
- Why does contiguous memory matter?


Answer:

1. '.shape' represents a tuple representing the dimensions of the array
2. Contiguous memory is important because it allows for fast access to elements in the array. With just the index we can retrieve the element in the array.

Section 1.2 — dtype & Memory

In [11]:
# TODO:
# Create two arrays with same values but different dtypes
base = np.arange(100)
arr_int = base.astype(np.int64)
arr_float = base.astype(np.float64)
print('int :', arr_int)
print('float :', arr_float)


int : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
float : [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [17]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print('int bytes: ', arr_int.nbytes)
print('float bytes: ', arr_float.nbytes)

int bytes:  800
float bytes:  800


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?

Answer: It matters because if we have chose a wrong datatype then it will consume a lot of computer resources and that would become slower since cache is not being hit properly.


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [19]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(20).reshape(10, 2)
A_slice = A[::2]
A_slice


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [21]:
# TODO:
# Modify A_slice and observe A
A_slice[0, 0] = -999

A_copy = A[[0, 2, 4]]
A_copy[0, 0] = 123456
print('A :', A)
print('A_copy :', A_copy)


A : [[-999    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]
 [  10   11]
 [  12   13]
 [  14   15]
 [  16   17]
 [  18   19]]
A_copy : [[123456      1]
 [     4      5]
 [     8      9]]


Explain:
- Why did the original array change (or not)?

Answer: The original array changed because A and A_slice they share the memory so when we changed an element in A_slice original array also changed. One was a view and another was copy so it did not change in the copy

Section 2.2 — Boolean Masking

In [22]:
# TODO:
# Create random array of size 1000

range = np.random.default_rng(0)
X = range.standard_normal(1000)


array([ 1.25730221e-01, -1.32104863e-01,  6.40422650e-01,  1.04900117e-01,
       -5.35669373e-01,  3.61595055e-01,  1.30400005e+00,  9.47080963e-01,
       -7.03735236e-01, -1.26542147e+00, -6.23274463e-01,  4.13259793e-02,
       -2.32503077e+00, -2.18791664e-01, -1.24591095e+00, -7.32267355e-01,
       -5.44258983e-01, -3.16300156e-01,  4.11630536e-01,  1.04251337e+00,
       -1.28534663e-01,  1.36646347e+00, -6.65194673e-01,  3.51510070e-01,
        9.03470182e-01,  9.40122978e-02, -7.43499249e-01, -9.21725376e-01,
       -4.57725826e-01,  2.20195123e-01, -1.00961818e+00, -2.09175575e-01,
       -1.59225010e-01,  5.40845585e-01,  2.14659123e-01,  3.55372709e-01,
       -6.53828609e-01, -1.29613634e-01,  7.83975470e-01,  1.49343115e+00,
       -1.25906553e+00,  1.51392377e+00,  1.34587542e+00,  7.81311401e-01,
        2.64455630e-01, -3.13922815e-01,  1.45802068e+00,  1.96025832e+00,
        1.80163487e+00,  1.31510376e+00,  3.57380411e-01, -1.20831863e+00,
       -4.45413312e-03,  

In [23]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask

mean = X.mean()
above_mean = X[X > mean]
print(above_mean)

[ 1.25730221e-01  6.40422650e-01  1.04900117e-01  3.61595055e-01
  1.30400005e+00  9.47080963e-01  4.13259793e-02  4.11630536e-01
  1.04251337e+00  1.36646347e+00  3.51510070e-01  9.03470182e-01
  9.40122978e-02  2.20195123e-01  5.40845585e-01  2.14659123e-01
  3.55372709e-01  7.83975470e-01  1.49343115e+00  1.51392377e+00
  1.34587542e+00  7.81311401e-01  2.64455630e-01  1.45802068e+00
  1.96025832e+00  1.80163487e+00  1.31510376e+00  3.57380411e-01
 -4.45413312e-03  6.56474935e-01  3.95122060e-01  4.29863695e-01
  6.96042724e-01  1.73936788e+00  3.28969629e-01  1.58347288e+00
  1.32036099e+00  6.33352623e-01  5.20289743e-02  6.83686191e-01
  1.00396158e+00  1.82201136e+00  9.35049988e-01  4.90546138e-02
  2.00239258e+00  1.88519193e-01  6.30411491e-01  5.81165812e-01
  1.29455882e+00  1.68910745e+00  1.57440828e+00  2.49785372e-01
  1.03145308e+00  1.61009577e-01  5.02682850e-01  9.89713033e-01
  8.73042153e-01  6.21017854e-01  3.86369598e-01  1.09279697e-01
  2.02114395e-01  6.94171

In [24]:
# TODO:
# Replace negative values with 0 (no loops)
X_copy = X.copy()
X_copy[X_copy < 0] = 0

print('Mean :', mean)
print('Above mean count : ', above_mean.size)
print('Negatives after replacing :', (X_copy < 0).sum())


Mean : -0.04802827676298692
Above mean count :  488
Negatives after replacing : 0


Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [35]:
# TODO:
# Create A (1000, 50) and b (50,)
range = np.random.default_rng(1)
A = range.standard_normal((1000, 50))
b = range.standard_normal(50,)
print('A shape :', A.shape)
print('b shape :', b.shape)


A shape : (1000, 50)
b shape : (50,)


In [36]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required
A_plus = A + b

print('A :', A)
print('b :', b)
print('A_plus :', A_plus)

A : [[ 0.34558419  0.82161814  0.33043708 ... -0.50629166  0.59374807
   0.89116695]
 [ 0.3208483  -0.81823023  0.73165228 ...  0.0330001  -1.42534896
   0.33281361]
 [-0.65128101  0.8624448  -0.12559208 ...  0.42514874  0.28241584
  -1.15929673]
 ...
 [ 2.63806388  0.1786702  -1.503011   ... -0.89979321 -1.09720577
   2.45949873]
 [ 0.25460571 -0.64984191  0.02022446 ...  0.69710746 -1.57753933
  -0.47634927]
 [-0.4769489  -0.49410047 -0.81352119 ... -0.38350551 -0.34688599
  -0.18918713]]
b : [-0.02215035  0.42352295  0.83961772  0.13917553  1.63394651 -0.76185535
 -0.46289533  0.32236092  0.12571245  0.47426305  0.05006911  0.70806523
  0.01446776 -1.68793899  0.21504247 -0.82351637  0.80367564  0.92058909
 -0.23200302 -2.04936228  1.60474282 -0.27090957  0.34082181 -1.19988925
 -0.66366466 -1.1153355   0.79699651  2.02121366 -1.37273641 -0.75996509
 -0.72778754 -1.65573038 -1.10682092  0.53172428 -0.23391387 -0.73098463
  1.81925951  1.76574199 -0.65318475  1.10633212 -0.20341185 -

In [37]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind
row_mean = A.mean(axis = 1, keepdims = True)
row_std = A.std(axis = 1, keepdims = True)
A_norm = (A - row_mean)/row_std
A_norm.shape


(1000, 50)

Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [55]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it
col = np.arange(1000)
try:
  _ = A - col
except ValueError as e:
  print('Expected broadcasting error :', e)
col2 = col.reshape(-1, 1)
A_fixed = A - col2
print(A_fixed.shape)

Expected broadcasting error : operands could not be broadcast together with shapes (1000,50) (1000,) 
(1000, 50)


What was wrong with the original shapes?

Answer: The shapes did not match. We were comparing 1000 to 50 and so it gave error. The moment we reshaped it worked.

Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [56]:
# TODO:
# Create large array X of size 1,000,000
range = np.random.default_rng(2)
X = range.standard_normal(1_000_000)
print(X.shape)

(1000000,)


In [59]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
import builtins
mu = X.mean()
sigma = X.std()
t0 = time.time()
out_loop = np.empty_like(X)
for i in builtins.range(X.shape[0]):
  out_loop[i] = (X[i] - mu) / sigma
time_taken = time.time() - t0
print(round(time_taken, 4))

0.4173


In [61]:
# TODO:
# Normalize using vectorization
t1 = time.time()
out_vec = (X - mu)/sigma
vec_time = time.time() - t1
round(vec_time, 4)
print(round(time_taken/max(vec_time, 1e-12), 1))
print('allclose :', np.allclose(out_loop, out_vec))


117.6
allclose : True


Why is vectorization faster?

Answer: Because for loops the datatypes is left for system to decide and also we have to iterate through all the elements, while vectorization performs operations parallely.

Task 4.2: Pairwise Distance (FAANG Classic)

In [5]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
  sq = np.sum(X * X, axis = 1, keepdims = True)
  dist = sq + sq.T - 2 * (X @ X.T)
  dist = np.maximum(dist, 0.0)
  return np.sqrt(dist)

rng = np.random.default_rng(3)
Xsmall = rng.standard_normal((200, 10))
D = pairwise_distance(Xsmall)
print(D.shape)


(200, 200)


Section 5 — Numerical Stability

Task 5.1: Softmax

In [8]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
  ex = np.exp(X)
  print(ex)
  return ex/ex.sum(axis = 1, keepdims = True)

Xbig = np.array([[1000.0, 1001.0, 1002.0]])
try:
  softmax_naive(Xbig)
except FloatingPointError as e:
  print('overflow :', e)

[[inf inf inf]]


/tmp/ipython-input-2121255304.py:5: RuntimeWarning: overflow encountered in exp
  ex = np.exp(X)
/tmp/ipython-input-2121255304.py:7: RuntimeWarning: invalid value encountered in divide
  return ex/ex.sum(axis = 1, keepdims = True)


In [13]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    Z = X - X.max(axis = 1, keepdims = True)
    ex = np.exp(Z)
    return ex/ex.sum(axis = 1, keepdims = True)

print('stable :', softmax_stable(Xbig))
print('rowSum :', softmax_stable(Xbig).sum(axis = 1))

stable : [[0.09003057 0.24472847 0.66524096]]
rowSum : [1.]


Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [16]:
# TODO:
# Try valid and invalid matrix multiplications
A = np.random.default_rng(3).standard_normal((3,4))
B = np.random.default_rng(4).standard_normal((4,2))
mat_mul = A @ B
print(mat_mul.shape)

try:
  _ = A @ A
except ValueError as e:
  print('Invalid matrix multiplication: ', e)
print(' A @ B == dot.product', np.allclose(np.dot(A,B), mat_mul))
print('matmul == A @ B', np.allclose(np.matmul(A,B), mat_mul))

(3, 2)
Invalid matrix multiplication:  matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)
 A @ B == dot.product True
matmul == A @ B True


Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [17]:
# TODO:
# Solve Ax = b and verify solution
rng = np.random.default_rng(6)
A = rng.standard_normal((5, 5))
b = rng.standard_normal((5,))
x = np.linalg.solve(A, b)
resid = np.linalg.norm(A @ x - b)
print('residual', resid)

residual 1.7702748954631059e-15


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [28]:
# TODO:
# Compare in-place vs out-of-place operations
X = np.random.default_rng(7).standard_normal((2_000_000))
Y = X.copy()
t0 = time.time()
Z = X + 1.0
t_out = time.time() - t0
t1 = time.time()
Y += 1.0
t_in = time.time() - t1
print('out-of-place :', round(t_out, 4))
print('in-place :', round(t_in, 4))
print(X)
print(Z)


out-of-place : 0.0067
in-place : 0.0018
[ 1.23015336e-03  2.98745538e-01 -2.74137855e-01 ...  1.60016473e+00
 -3.72619136e-01 -4.37221960e-01]
[1.00123015 1.29874554 0.72586214 ... 2.60016473 0.62738086 0.56277804]


Task 7.2: Strides

In [30]:
# TODO:
# Inspect array strides and explain

A = np.arange(24).reshape(6, 4)
print('shape :', A.shape, 'strides :', A.strides)
B = A[:, ::2]
print('shape :', B.shape, 'strides :', B.strides)

shape : (6, 4) strides : (32, 8)
shape : (6, 2) strides : (32, 16)


Section 8 — Mini Case Study

In [31]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors
range = np.random.default_rng(8)
X = range.standard_normal((10_000, 100))
# Normalize
mu = X.mean(axis = 0, keepdims = True)
sigma = X.std(axis = 0, keepdims = True)
Xn = (X - mu)/sigma
# Covariance
Covariance = (Xn.T @ Xn) / (Xn.shape[0] - 1)
# Top-k Eigenvectors
eigvals, eigvecs = np.linalg.eigh(Covariance)
k = 5
top_idx = np.argsort(eigvals)[-k:][::-1]
top_idx


array([99, 98, 97, 96, 95])

Explain each step and its ML relevance.


1. Where did NumPy save memory?

Answer: NumPy saves the memory by storing data in contiguous memory.

2. Where did it avoid Python overhead?

Answer: It avoided python overhead in vectorized operations

3. Which operation would break at scale?

Answer: Something that uses loops and O(n2) will break